// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDa0r3vf7ZEimHFk6NjxTr9UEs5qL3VTXg',
    appId: '1:536011456572:web:175983dc3a23d4c0f5c339',
    messagingSenderId: '536011456572',
    projectId: 'evently-b793d',
    authDomain: 'evently-b793d.firebaseapp.com',
    storageBucket: 'evently-b793d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeJFQW41cL1cbNP5KvVWe-62kKvJpjB8U',
    appId: '1:536011456572:android:b1c8c26665a89101f5c339',
    messagingSenderId: '536011456572',
    projectId: 'evently-b793d',
    storageBucket: 'evently-b793d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTBxWHn0C1XN0kyu6PrvIUvKJVUwVlbhI',
    appId: '1:536011456572:ios:7d2eb9b1fde5cf4cf5c339',
    messagingSenderId: '536011456572',
    projectId: 'evently-b793d',
    storageBucket: 'evently-b793d.firebasestorage.app',
    iosBundleId: 'com.example.evently',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTBxWHn0C1XN0kyu6PrvIUvKJVUwVlbhI',
    appId: '1:536011456572:ios:7d2eb9b1fde5cf4cf5c339',
    messagingSenderId: '536011456572',
    projectId: 'evently-b793d',
    storageBucket: 'evently-b793d.firebasestorage.app',
    iosBundleId: 'com.example.evently',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDa0r3vf7ZEimHFk6NjxTr9UEs5qL3VTXg',
    appId: '1:536011456572:web:600feef3d6405c69f5c339',
    messagingSenderId: '536011456572',
    projectId: 'evently-b793d',
    authDomain: 'evently-b793d.firebaseapp.com',
    storageBucket: 'evently-b793d.firebasestorage.app',
  );
}
